### ISSUE TITLE
Когда будет версия для C#?

### ISSUE THREAD

**Issue by Temka193** [JetBrains/rd#1]
Собственно, хотелось бы узнать, когда вы опубликуете C# версию ?

**Comment by korifey** [comment]
@Temka193 Даже нормальную документацию времени сделать пока нет, ключевые участники публикации open-source перегружены текущими обязанностями.  По C# осталось работы на 3-5 дней, время для неё зарезервировано на июль.

**Comment by Temka193** [comment]
Уже июль?)

**Comment by Temka193** [comment]
Уже август) Вы перенесли дату?

**Comment by EgorBo** [comment]
😢

**Comment by yole** [comment]
Версия для C# будет тогда, когда она будет готова. На данный момент у нас другие приоритеты. Пожалуйста, не надо посылать нам бессмысленных комментариев.

**Comment by korifey** [comment]
Версия для С# готова и выложена.
