### ISSUE TITLE
Fusion might be a good alternative to this :)

### ISSUE THREAD

**Issue by alexyakunin** [JetBrains/rd#152]
Hi guys, sorry for spamming here, but some of my friends send me links to this repository when I show them Fusion: https://github.com/servicetitan/Stl.Fusion - and honestly, I didn't dig deeply into rd, but it looks like at least a part of the goals are similar.

So just FYI, there is a fancy alternative to this framework. It's truly free (MIT license) & you can always reach its author if you'll end up using it. The framework is built mostly with web apps in mind, but nothing nothing prevents to use it anywhere.

Options like getting a live (online) presentation with Q/A are open as well :)

**Comment by ForNeVeR** [comment]
Thanks for your suggestion!

Currently, we aren't interested in migration from Rd to other solutions.
