### ISSUE TITLE
JetBrains.Lifetimes: System.ArrayTypeMismatchException

### ISSUE THREAD

**Issue by vitidev** [JetBrains/rd#154]
I am tried JetBrains.Lifetimes + Microsoft.Extensions.DependencyInjection for learn

I pass lifetime(struct) to the constructor of the objects being created by container and got strange error when I use .Bracket

it works 2 times correctly, and the third time an error.

> System.ArrayTypeMismatchException: 'Attempted to access an element as a type incompatible with the array.'

![Image 7](https://user-images.githubusercontent.com/2243958/96453523-45d9f780-1223-11eb-817c-ad2d0143f95f.png)

within JetBrains.Lifetimes (LifetimeDefinition.cs)

![Image 5](https://user-images.githubusercontent.com/2243958/96453621-673ae380-1223-11eb-9426-0997c6d0b910.png)

Of course, I understand that lifetime is struct and it is not very correct to use it with IoC in this way, but I would like to understand the cause of the error.
Even if the IoC breaks the structure, but after all, lifetime only keeps a reference to the definition, to which the container has nothing to do.

I was unable to write test code with reproducible error, but I shrink project where it still reproduces

netcore 3.1, JetBrains.Lifetimes 2020.2.3 (or this repo), win 10 x64, WPF, vs2019

**Comment by ForNeVeR** [comment]
Could you check types of `action` and `myResources` at the second screenshot? Are they really incompatible?

`myResources` is supposed to be an object array.

**Comment by ForNeVeR** [comment]
Very strange. Could you share the code you're reproducing the issue with?

**Comment by vitidev** [comment]
@ForNeVeR 

Yes. As result I was able to remove almost everything that could be removed unnecessary.
Now it need to check if this is an error not only on my system
https://github.com/vitidev/JetbrainsLifetimeArrayTypeMismatch

**Comment by vitidev** [comment]
@ForNeVeR 

>I'd recommend you to raise issue on dotnet/runtime repository about this DI behavior; probably it is something they should defend against better.

They seem [to know](https://github.com/dotnet/extensions/issues/2431).
