### ISSUE TITLE
Support a way to append annotations to rd model types

### ISSUE THREAD

**Issue by kashmervil** [JetBrains/rd#157]
The current problem is with @Nls annotations, this, however, can be useful for other cases.
e.g. we need a way to do something similar t this
`property("title", string.Nls(Title))`

**Comment by kashmervil** [comment]
This is a stopper for https://youtrack.jetbrains.com/issue/CWM-1227

**Comment by denis417** [comment]
Added annotations for Kotlin Generator and partially c#.
See `nlsSafeString`, `nonNlsString` and `nlsString`. Also function was added: `attrs(KnownAttrs)` for `IScalar` types.
Examples:
```
field("string", string.nullable.attrs(KnownAttrs.Nls))
field("string", nlsString)
```
