### ISSUE TITLE
Need a way to define different termination timeout for nested lifetimes

### ISSUE THREAD

**Issue by IlyaAI** [JetBrains/rd#265]
We've tried to use Lifetime's async-features in dotMemory and DPA instead of our own implementation of AsyncLifetime and faced the problem: 500ms of current default timeout isn't enough for DM/DPA activities. While DM is standalone product we can solve this by globally overriding LifetimeDefinition.WaitForExecutingInTerminationTimeoutMs. But for DPA this way looks unacceptable because DPA works side-by-side with Rider/R#. So we need a way to  define different termination timeout for nested lifetimes (associated with DPA components, for example).

**Comment by korifey** [comment]
I see several ways to achieve it: 

1. The worst one - add separate int field `timeout` into LifetimeDefinition. This will make every lifetime 4 bytes bigger.
2. Use some internal bits of lifetime's state field for this timeout in logarithmic scale: 001 = 1ms, 010 = 2ms, 011 = 4ms, 100 = 8ms, etc 
3. Make cookie (thread local entity `Timeout`) instead  global static - and use it in `Terminate` method
4. Add optional parameter into Lifetime's `Terminate` method

**Comment by IlyaAI** [comment]
I'm used a variation of (2): using internal bits, but instead of log scale I introduced 'semantic' timeout (aka short, long, extra-long) with actual values defined statically via LifetimeDefinition.SetTerminationTimeoutMs
See https://github.com/JetBrains/rd/pull/266

**Comment by ForNeVeR** [comment]
Closed by #266.
