### ISSUE TITLE
Lifetimes are awesome!!!

### ISSUE THREAD

**Issue by dmitry-bym** [JetBrains/rd#479]
When seen that first time just fall in love =) Use lifetimes in maui application, wanted use signals (cause it force to use lifetime to advice), but had to switch back to Rx.NET just because observables can be completed. So I integrated lifetimes to observables and for now it looks so:
```c#
    _someObservable.Subscribe(lifetime, action);
```
or
```c#
    _someObservable.Subscribe(action).DisposeWith(lifetime);
```
So now its a charm to manage disposable cause before it was a pain (you know)
```c#
private IDisposable? _sub;

private void Foo()
{
    _sub?.Dispose(); 
    _sub = _someObservable.Subscribe(action)
}

public void Dispose()
{
    _sub?.Dispose()
}
```
And thats only when one disposable =), also SequentialLifetimes useful too.
No issues just wanted to say thanks for ur work!

**Comment by ForNeVeR** [comment]
Thank you for your wonderful feedback. It is very pleasant to hear that you are enjoying our library.

Is your work on Rx integration available somewhere online?

**Comment by dmitry-bym** [comment]
Not at the moment, but if it can be interesting to someone i can publish whats possible. So basically what i can publish now as a draft (cause it was done in rush mode) is just bunch of extensions for Observables, and some Sources (needed an ability to create sources from result and do select etc.) I also imbued the entire application cycle with lifetimes and much more =):
```c#
public partial class SomeViewModel
{
    public SomeViewModel([ApplicationLifetime] Lifetime lifetime)
    {
        ...
    }
}
```
But can't publish now cause It's highly coupled with app, and need some time to split that - so if someone need that will do that later

**Comment by ForNeVeR** [comment]
I have been using lifetimes in a couple of projects that also use Rx, so I would say it looks useful. But it is of course your code, so you are free to keep it as you like, open source or closed as project-specific.

Thanks for your nice feedback again.
