### ISSUE TITLE
NRE if task handler is not set

### ISSUE THREAD

**Issue by nerzhulart** [JetBrains/rd#85]
It's better to throw user friendly exception when the handler is missing

https://github.com/JetBrains/rd/blob/53d286d619cfcf46aa988381244f5a4bda0d9b3e/rd-net/RdFramework/Tasks/RdCall.cs#L89

**Comment by operasfantom** [comment]
That's bright idea! I wonder if you would implement it by yourself

**Comment by ForNeVeR** [comment]
I believe, this was fixed by #202.
